@ECHO OFF
ECHO THIS BATCH IS FOR DEBUGGING THE EXECUTABLE JAR ONLY
ECHO DOUBLE-CLICK THE "Toms Suite.jar" TO RUN IT
ECHO -
ECHO Generated by: JAR Maker (http://www.goldenstudios.or.id/)
@ECHO ON
java -jar Toms_Suite.jar
@ECHO OFF
pause
